version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: vectortest
    ports:
      - "3306:3306"

  mariadb:
    image: mariadb:10.11
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: vectortest
    ports:
      - "3307:3306"

  tidb:
    image: pingcap/tidb:v6.1.0
    ports:
      - "4000:4000" 