services:
  mysql:
    image: mysql:9.2
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: vectortest
    ports:
      - "13306:3306"

  mariadb:
    image: mariadb:11.7.1-rc
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: vectortest
    ports:
      - "13307:3306"

  tidb:
    image: pingcap/tidb:v8.5.1
    ports:
      - "14000:4000" 